import { WorldGenerator } from './shared/src/worldgen';
import { World } from './shared/src/world';
const g = new WorldGenerator(12345);
let t = performance.now();
const w = new World();
for (let x=-4;x<=4;x++) for (let z=-4;z<=4;z++) w.addChunk(g.generate(x,z));
console.log('81 chunks gen+light ms', (performance.now()-t).toFixed(0));
t = performance.now();
for (let x=5;x<=8;x++) for (let z=-4;z<=4;z++) g.generate(x,z);
console.log('36 chunks gen only ms', (performance.now()-t).toFixed(0));
console.log('spawn', g.findSpawn());
const counts: Record<number, number> = {};
for (const c of w.chunks.values()) for (const b of c.biomes) counts[b]=(counts[b]||0)+1;
console.log(counts);
t = performance.now();
for (let i=0;i<200;i++) w.setBlock(i%16, 70, 3, i%2?1:0);
console.log('200 setblocks ms', (performance.now()-t).toFixed(1));
